### ISSUE TITLE
AAR/JAR build request

### ISSUE THREAD

**Issue by fbis251** [varunest/SparkButton#1]
Do you have plans for supporting a maven/jitpack build of your library? It would make including your library in other projects easier

I can open a pull request for a jitpack based build

**Comment by varunest** [comment]
I have already put up a request on Sonatype, it is taking some time to process. Meanwhile if it isn't much of a hassle, you can put up a pull request for jitpack.

**Comment by varunest** [comment]
No worries, I have uploaded the aar on Jitpack. Can I close the issue now?
