### ISSUE TITLE
Which item is selected on RecyclerView

### ISSUE THREAD

**Issue by WrathChaos** [varunest/SparkButton#11]
Hello,
Firstly thank you for this library, i love it and its really simple to implement. I use this on my recyclerview but i have problem to get which sparkButton is selected or not. I'm using a textview and sparkButton in one line so i need to get that textview's text from all selected SparkButtons.

Please help me, thank you :)

**Comment by varunest** [comment]
@WrathChaos, Sorry for the late response. I have added a function isChecked() in the SparkButton which can be called to check the state.
