### ISSUE TITLE
No resource identifier found for attribute 'sparkbutton_inactiveImage'

### ISSUE THREAD

**Issue by shaishavgandhi05** [varunest/SparkButton#2]
Somehow, adding the app:sparkbutton_inactiveImage property in XML causes my whole project to break down. I get the above mentioned error. No amount of project cleaning and building changes it. Any known issues? 

My Code : 

<com.varunest.sparkbutton.SparkButton
 android:id="@+id/spark_button"
 android:layout_width="40dp"
 android:layout_height="40dp"
 app:sparkbutton_activeImage="@drawable/ic_info_black_24dp"
 app:sparkbutton_inactiveImage="@drawable/ic_info_outline_white_24dp"/>

The drawables are present in my project

**Comment by varunest** [comment]
I think its typo error. Make sure you are using : 

app:sparkbutton_inActiveImage

and not 

app:sparkbutton_inactiveImage

**Comment by varunest** [comment]
I see, i've made the same mistake in the readme as well. Have fixed it. Thanks.

**Comment by shaishavgandhi05** [comment]
Awesome. Works now :)
