### ISSUE TITLE
Sparks are not antialiased

### ISSUE THREAD

**Issue by connyduck** [varunest/SparkButton#21]
I really like this library but the spark animation looks somewhat blurry. After taking a screenshot I noticed that the drawn circles are not antialiased

This is probably solved by adding `setAntiAlias(true)` to the used `Paint`s.
If you want I can try to provide a pull request.

Zoomed in screenshot of animation in progress. 
![screenshot_20170806-094952 1](https://user-images.githubusercontent.com/10157047/29001753-71a9a142-7a93-11e7-9140-d759ca5388e5.png)

**Comment by varunest** [comment]
Yeah.. it would be great if you can put up a pull request. I will release it on jitpack as soon as i merge it.
