### ISSUE TITLE
How to add click listener?

### ISSUE THREAD

**Issue by jinfagang** [varunest/SparkButton#24]
Hi, thanks for this beautiful library, I have only one question, how to set on a click listener on the SparkButton. I try find it and set on click, however, all the animation are gone after do this. I think I am not using it properly??

**Comment by jinfagang** [comment]
Sorry, I found it. Sorry for bothering!

**Comment by MuhammadFaisalIchal** [comment]
@jinfagang hello jinfagang, would you tell how and where it is?
