### ISSUE TITLE
Disable Listener on Button

### ISSUE THREAD

**Issue by smholsen** [varunest/SparkButton#25]
Hi!
Thank you very much for this project, it is amazing :)
I was wondering if there is any possibility to disable the original onClick listener on the button, which initiates the animation. I am trying to use the button, but only toggling it when the user clicks another view, so I do not want the animation to play when the buttonview is clicked. 
Are there any way of obtaining this functionality?
I tried wrapping it in a  "non clickable" relative Layout, but that did not seem to work.
Best regards

**Comment by varunest** [comment]
@smholsen Did you try wrapping the button in **clickable** container (ex. FrameLayout). Theoritically it should consume touch instead of passing the event to **SparkButton**

**Comment by smholsen** [comment]
What a great idea, I will see if it works when I get home :)
Thank you very much.

**Comment by smholsen** [comment]
Unfortunately, this did not seem to work. I am not sure why though. 
I tried with different variations of this

                <FrameLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentEnd="true"
                    android:layout_alignParentLeft="false"
                    android:layout_alignParentRight="true"
                    android:layout_alignParentStart="false"
                    android:layout_alignParentTop="true"
                    android:clickable="true"
                    android:focusable="true">
                    <com.varunest.sparkbutton.SparkButton
                        android:id="@+id/lockScreenSettingBtn"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        app:sparkbutton_activeImage="@drawable/ic_screen_green"
                        app:sparkbutton_iconSize="40dp"
                        app:sparkbutton_inActiveImage="@drawable/ic_screen_gray"
                        app:sparkbutton_primaryColor="@color/ok_green"
                        app:sparkbutton_secondaryColor="@color/not_gray">
                    </com.varunest.sparkbutton.SparkButton>
                </FrameLayout>

But I was not able to find a solution where the touch event did not pass through to the SparkButton.

**Comment by smholsen** [comment]
I found a solution where I could extend the parent ViewGroup, (In my case a RelativeLayout), and override the _onInterceptTrouchEvent_ method. 

```
class settingsViewGroup extends RelativeLayout {
    public settingsViewGroup(Context context) {
        super(context);
    }
    public settingsViewGroup(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        // Do not propagate the click do children
        return true;
        // return super.onInterceptTouchEvent(ev);
    }
}
```

Seemed to work fine :)

**Comment by basti12354** [comment]
@smholsen  Can you provide your complete solution. I am running into the same problem atm 
Thank you ;)

**Comment by smholsen** [comment]
The project I am working on is unfortunately not open source, but I'll try to shed some more light if I can, and just ask further if something is unclear.

So what I did was to create an extension of the RelativeLayout view, so I could modify it a little bit. The only modification here is that it intercepts all TouchEvents (as we do not call the super). So this is the entire class, which you place inside your package. 

```
import android.content.Context;
import android.util.AttributeSet;
import android.view.MotionEvent;
import android.widget.RelativeLayout;


class settingsViewGroup extends RelativeLayout {
    public settingsViewGroup(Context context) {
        super(context);
    }
    public settingsViewGroup(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        // Do not propagate the click do children
        return true;
        // return super.onInterceptTouchEvent(ev);
    }
}
```

So now that you have created your new Layout you can use this in your View, and wrap it around your SparkButton. 

```
            <com.youdomain.yourproject.settingsViewGroup
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
            >


                <com.varunest.sparkbutton.SparkButton
                    ...
                >

                </com.varunest.sparkbutton.SparkButton>

            </com.youdomain.yourproject.settingsViewGroup>
```
And the touchevents will now not prpagate further than your outer Layout. (com.youdomain.yourproject.settingsViewGroup). 

Hope this cleared it up. 
If you want to see my example, I used it in the Settings view in this app (work in progress 😄 ): 
https://sleeptimerforandroid.com/ 
Or on the play store: https://play.google.com/store/apps/details?id=com.smholsen.sleeptimerallmedia
