### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by kshivam654** [varunest/SparkButton#27]
what is context in the java code below.............
SparkButton button = new SparkButtonBuilder(context)
						.setActiveImage(R.drawable.active_image)
						.setInActiveImage(R.drawable.inactive_image)
						.setPrimaryColor(ContextCompat.getColor(context, R.color.primary_color))
						.setSecondaryColor(ContextCompat.getColor(context, R.color.secondary_color))
						.build();

**Comment by varunest** [comment]
It is the activity's context in which you are trying to inflate this view.
