### ISSUE TITLE
Error inflating class com.varunest.sparkbutton.SparkButton

### ISSUE THREAD

**Issue by SilverFoxA** [varunest/SparkButton#28]
`Binary XML file line #230: Error inflating class com.varunest.sparkbutton.SparkButton`

 ` <com.varunest.sparkbutton.SparkButton
                                        android:id="@+id/star_button1"
                                        android:layout_width="25sp"
                                        android:layout_height="25sp"
                                        android:layout_marginLeft="5sp"
                                        android:layout_marginStart="5sp"
                                        app:sparkbutton_activeImage="@drawable/ic_liked"
                                        app:sparkbutton_animationSpeed=".85"
                                        app:sparkbutton_iconSize="25sp"
                                        app:sparkbutton_inActiveImage="@drawable/ic_like" />`

**Comment by edgelv34** [comment]
me too.. how solved?

**Comment by SilverFoxA** [comment]
I have used one of the forks of this library

**Comment by alexatbooli** [comment]
But you've used sp instead of dp for dimensions... they only apply to fonts.
