### ISSUE TITLE
Event Listener / Click Listener didn't work

### ISSUE THREAD

**Issue by MuhammadFaisalIchal** [varunest/SparkButton#29]
Hello, thanks for this beautiful button.

By the way, i intended to make this button when clicked, it move to another layout.

i tried to use your guidance as:
###Event Listener
```
sparkButton.setEventListener(new SparkEventListener(){
		@Override
		void onEvent(ImageView button, boolean buttonState) {
			if (buttonState) {
				// Button is active
			} else {
				// Button is inactive
			}
		}
});

```
It didn't work, instead showing error that says:

error: <anonymous com.example.android.myapplication.MainActivity$1> is not abstract and does not override abstract method onEventAnimationStart(ImageView,boolean) in SparkEventListener

error: onEvent(ImageView,boolean) in <anonymous com.example.android.myapplication.MainActivity$1> cannot implement onEvent(ImageView,boolean) in SparkEventListener attempting to assign weaker access privileges; was public

**Comment by hammadshah1995** [comment]
use this and then the methods will work

  sparkbutton=(SparkButton) findViewById(R.id.spark_button);

**Comment by MuhammadFaisalIchal** [comment]
Well thanks a lot @hammadshah1995 it does work.
But actually, the animation didn't work as expected, because of intent made quick move of activities.

i tried to apply delay on it but it only delay the moves of activities but the animation wasn't played, it paused.

So then i think to find other way to play the animation by put it first, before we click the button.
Do you have another solution?

**Comment by jillv** [comment]
Hi @MuhammadFaisalIchal how do you solve this? I have the same problem.
