### ISSUE TITLE
Using setColors at runtime does not actually change the colors used during animation

### ISSUE THREAD

**Issue by TheStarterPack** [varunest/SparkButton#31]
Basically as the title says, i change the colors during runtime in a viewholder but the animation color stays the same. Changing the Icons works, however.

**Comment by varunest** [comment]
@peterivitz opened a pullrequest to solve this issue. I have merged it into master. Can you check if this is fixed for you now?

**Comment by TheStarterPack** [comment]
yes, with 1.0.6 it works just as expected!
