### ISSUE TITLE
scroll through sparkbutton will 

### ISSUE THREAD

**Issue by aaaking** [varunest/SparkButton#7]
i write code like this:
```
               view.findViewById(R.id.star_button1).setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        Log.i("test", "sparkbutton click");
                        ((SparkButton) v).playAnimation();
                    }
                });
```
then if I scroll through this sparkbutton(R.id.star_button1) while not click this sparkbutton(R.id.star_button1), then the log will be printed and animation will play. How can I print the log and play the animation only in click situation and not in scroll through situation?

**Comment by varunest** [comment]
Instead of setting click listener, use event listener as stated in docs for listening click events. 
```
SparkButton button = (SparkButton)view.findViewById(R.id.star_button1);
buttons.setEventListener(...);
```

**Comment by aaaking** [comment]
ok, thanks
